# Generated by Django 4.2 on 2023-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_career_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_img',
            field=models.ImageField(upload_to='job'),
        ),
    ]
