# Generated by Django 4.2 on 2023-05-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_jobs_job_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_on',
            new_name='Booked_On',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='Booking_Date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='Doctor_Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='Patient_Contact',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='Patient_Email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='Patient_Name',
        ),
    ]
