# Generated by Django 4.2 on 2023-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=250)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
